g++ -o ./assembler ./src/mainAssembler.cpp ./src/assembler.cpp ./src/instruction.cpp ./src/lexer.cpp ./src/parser.cpp ./src/symbolsTable.cpp ./src/relocationsTable.cpp
g++ -o ./linker ./src/mainLinker.cpp ./src/linker.cpp ./src/symbolsTable.cpp ./src/relocationsTable.cpp
g++ -o ./emulator ./src/mainEmulator.cpp ./src/emulator.cpp 
